-- ============================================================
-- Migration: Panel rate-limit hardening
-- Adds atomic server-side rate limiting for panel auth/API traffic.
-- No raw IPs, access codes, or bearer tokens are stored.
-- ============================================================

ALTER TABLE public.private_panel_login_attempts
  ADD COLUMN IF NOT EXISTS code_fingerprint TEXT;

CREATE INDEX IF NOT EXISTS idx_private_panel_login_attempts_code
  ON public.private_panel_login_attempts (code_fingerprint, attempted_at DESC)
  WHERE code_fingerprint IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.private_panel_rate_limit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_hash TEXT NOT NULL,
  scope TEXT NOT NULL,
  attempted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT private_panel_rate_limit_actor_hash_len CHECK (char_length(actor_hash) BETWEEN 32 AND 128),
  CONSTRAINT private_panel_rate_limit_scope_len CHECK (char_length(scope) BETWEEN 1 AND 80)
);

CREATE INDEX IF NOT EXISTS idx_private_panel_rate_limit_lookup
  ON public.private_panel_rate_limit_events (actor_hash, scope, attempted_at DESC);

CREATE INDEX IF NOT EXISTS idx_private_panel_rate_limit_time
  ON public.private_panel_rate_limit_events (attempted_at);

ALTER TABLE public.private_panel_rate_limit_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.private_panel_rate_limit_events FROM anon, authenticated;
GRANT ALL ON TABLE public.private_panel_rate_limit_events TO service_role;

COMMENT ON TABLE public.private_panel_rate_limit_events IS
  'Atomic panel rate-limit buckets. actor_hash is a keyed one-way identifier; raw IPs, tokens and access codes are never stored.';

CREATE OR REPLACE FUNCTION public.panel_check_rate_limit(
  p_actor_hash TEXT,
  p_scope TEXT,
  p_limit INTEGER,
  p_window_seconds INTEGER
)
RETURNS TABLE (
  allowed BOOLEAN,
  retry_after_seconds INTEGER,
  current_count INTEGER
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_now TIMESTAMPTZ := clock_timestamp();
  v_cutoff TIMESTAMPTZ;
  v_count INTEGER := 0;
  v_oldest TIMESTAMPTZ;
BEGIN
  IF p_actor_hash IS NULL OR char_length(p_actor_hash) < 32 THEN
    RAISE EXCEPTION 'invalid actor hash';
  END IF;
  IF p_scope IS NULL OR char_length(p_scope) < 1 OR char_length(p_scope) > 80 THEN
    RAISE EXCEPTION 'invalid scope';
  END IF;
  IF p_limit < 1 OR p_limit > 10000 THEN
    RAISE EXCEPTION 'invalid limit';
  END IF;
  IF p_window_seconds < 1 OR p_window_seconds > 86400 THEN
    RAISE EXCEPTION 'invalid window';
  END IF;

  v_cutoff := v_now - make_interval(secs => p_window_seconds);

  -- Serialize checks for the same actor/scope so parallel requests cannot
  -- bypass the count-then-insert boundary.
  PERFORM pg_advisory_xact_lock(hashtextextended(p_actor_hash || '|' || p_scope, 0));

  -- Opportunistic per-bucket cleanup keeps hot buckets bounded.
  DELETE FROM public.private_panel_rate_limit_events
   WHERE actor_hash = p_actor_hash
     AND scope = p_scope
     AND attempted_at < v_now - interval '24 hours';

  SELECT count(*), min(attempted_at)
    INTO v_count, v_oldest
    FROM public.private_panel_rate_limit_events
   WHERE actor_hash = p_actor_hash
     AND scope = p_scope
     AND attempted_at >= v_cutoff;

  IF v_count >= p_limit THEN
    allowed := false;
    current_count := v_count;
    retry_after_seconds := GREATEST(
      1,
      CEIL(EXTRACT(EPOCH FROM ((v_oldest + make_interval(secs => p_window_seconds)) - v_now)))::INTEGER
    );
    RETURN NEXT;
    RETURN;
  END IF;

  INSERT INTO public.private_panel_rate_limit_events (actor_hash, scope, attempted_at)
  VALUES (p_actor_hash, p_scope, v_now);

  allowed := true;
  retry_after_seconds := 0;
  current_count := v_count + 1;
  RETURN NEXT;
END;
$$;

REVOKE ALL ON FUNCTION public.panel_check_rate_limit(TEXT, TEXT, INTEGER, INTEGER) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.panel_check_rate_limit(TEXT, TEXT, INTEGER, INTEGER) TO service_role;

CREATE INDEX IF NOT EXISTS panel_sessions_active_event_idx
  ON public.panel_sessions (event_id, created_at DESC)
  WHERE revoked_at IS NULL;
